In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("../data/raw/spotify_artist_streaming_2020_2025.csv")
df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,...,popularity_category,loudness_category,key_name,mode_name,is_explicit_bool,release_quarter,is_weekend_release,log_stream_count,upbeat_score,artist_track_count
0,346d85e2-ffde-41b3-854a-589ed880b91f,Storm,Ethereal,The Hollow Journeys,2021-10-06,Pop,169594,47,0.6777,0.7949,...,Medium,Loud,A,Major,False,Q4,False,10.7492,0.6632,3232
1,12bc268a-363b-4f19-8fa8-0ced7ae1e462,Silent,The Wolfs,Ancient Thunder,2024-10-26,K-Pop,256755,26,0.9405,0.7163,...,Medium,Moderate,C#,Major,False,Q4,True,8.5895,0.7615,20
2,30d627d9-878d-4bb3-be59-71feb6ed4f3f,Shattered Lines,LolaOre,Twisted Harbors,2022-11-12,Punk,170212,46,0.6853,0.9500,...,Medium,Loud,E,Major,False,Q4,True,12.2935,0.7828,199
3,85501bb9-d221-4339-9e2e-29b1b3daff0a,Breaking Roses,Clay Black,The Blinding Letters,2020-06-22,Pop,181250,4,0.7817,0.6943,...,Low,Moderate,F#,Major,False,Q2,False,8.5658,0.6778,693
4,7bf92bd2-c6fe-4869-a90e-242bb8bbe7a3,Lines,Knot Hart,The Cosmic Letters,2024-01-22,Latin,160894,27,0.7200,0.4958,...,Medium,Moderate,C#,Major,False,Q1,False,10.2191,0.5494,12111

In [5]:
df.shape

(50000, 33)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50000 non-null  str
 1   track_name           50000 non-null  str
 2   artist_name          50000 non-null  str
 3   album_name           50000 non-null  str
 4   release_date         50000 non-null  str
 5   genre                50000 non-null  str
 6   duration_ms          50000 non-null  int64
 7   popularity           50000 non-null  int64
 8   danceability         50000 non-null  float64
 9   energy               50000 non-null  float64
 10  key                  50000 non-null  int64
 11  loudness             50000 non-null  float64
 12  mode                 50000 non-null  int64
 13  instrumentalness     50000 non-null  float64
 14  tempo                50000 non-null  float64
 15  stream_count         50000 non-null  int64
 16  country              50000 non-null  str
 17  explicit             50000 non-null  bool
 18  label                50000 non-null  str
 19  release_year         50000 non-null  int64
 20  release_month        50000 non-null  int64
 21  release_day_of_week  50000 non-null  str
 22  duration_minutes     50000 non-null  float64
 23  popularity_category  50000 non-null  str
 24  loudness_category    50000 non-null  str
 25  key_name             50000 non-null  str
 26  mode_name            50000 non-null  str
 27  is_explicit_bool     50000 non-null  bool
 28  release_quarter      50000 non-null  str
 29  is_weekend_release   50000 non-null  bool
 30  log_stream_count     50000 non-null  float64
 31  upbeat_score         50000 non-null  float64
 32  artist_track_count   50000 non-null  int64
dtypes: bool(3), float64(8), int64(8), str(14)
memory usage: 11.6 MB

In [7]:
df.describe()

,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,release_year,release_month,duration_minutes,log_stream_count,upbeat_score,artist_track_count
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,5.000000e+04,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,209814.455560,28.136820,0.661236,0.631853,5.47086,-7.669547,0.650280,0.055166,119.067461,1.183789e+05,2022.499620,6.528880,3.496915,9.835507,0.601615,4052.066320
std,44646.016547,15.999501,0.164143,0.168741,3.45610,2.621917,0.476886,0.095083,19.647807,5.658443e+05,1.709953,3.460926,0.744101,1.793877,0.105076,4817.780532
min,90000.000000,0.000000,0.000000,0.000000,0.00000,-18.620000,0.000000,0.000000,60.000000,1.000000e+02,2020.000000,1.000000,1.500000,4.615100,0.057800,2.000000
25%,179753.000000,16.000000,0.562400,0.523400,2.00000,-9.440000,0.000000,0.010300,105.990000,4.979750e+03,2021.000000,4.000000,3.000000,8.513350,0.542100,181.000000
50%,209689.000000,26.000000,0.675000,0.633400,5.00000,-7.660000,1.000000,0.025700,118.575000,1.595500e+04,2023.000000,7.000000,3.490000,9.677600,0.606400,1486.000000
75%,239708.250000,39.000000,0.775400,0.744700,8.00000,-5.880000,1.000000,0.057600,131.350000,6.068550e+04,2024.000000,10.000000,4.000000,11.013525,0.671100,5271.000000
max,388117.000000,92.000000,1.000000,1.000000,11.00000,0.000000,1.000000,1.000000,220.000000,4.334502e+07,2025.000000,12.000000,6.470000,17.584700,0.915400,12111.000000

In [8]:
df.isnull().sum()

track_id               0
track_name             0
artist_name            0
album_name             0
release_date           0
genre                  0
duration_ms            0
popularity             0
danceability           0
energy                 0
key                    0
loudness               0
mode                   0
instrumentalness       0
tempo                  0
stream_count           0
country                0
explicit               0
label                  0
release_year           0
release_month          0
release_day_of_week    0
duration_minutes       0
popularity_category    0
loudness_category      0
key_name               0
mode_name              0
is_explicit_bool       0
release_quarter        0
is_weekend_release     0
log_stream_count       0
upbeat_score           0
artist_track_count     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns.tolist()

['track_id',
 'track_name',
 'artist_name',
 'album_name',
 'release_date',
 'genre',
 'duration_ms',
 'popularity',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'instrumentalness',
 'tempo',
 'stream_count',
 'country',
 'explicit',
 'label',
 'release_year',
 'release_month',
 'release_day_of_week',
 'duration_minutes',
 'popularity_category',
 'loudness_category',
 'key_name',
 'mode_name',
 'is_explicit_bool',
 'release_quarter',
 'is_weekend_release',
 'log_stream_count',
 'upbeat_score',
 'artist_track_count']

In [11]:
df["genre"].value_counts()

genre
R&B            13273
Pop            12915
Hip-Hop         3930
Latin           2661
EDM             2407
Rock            2370
Folk            2249
Metal           1695
K-Pop           1384
Country         1294
Indie           1065
Trap             915
Jazz             810
Reggaeton        785
Alternative      759
Punk             384
Classical        357
Soul             325
Afrobeats        224
Disco            198
Name: count, dtype: int64

In [12]:
df["release_year"].value_counts().sort_index()

release_year
2020    8355
2021    8387
2022    8257
2023    8242
2024    8441
2025    8318
Name: count, dtype: int64

In [13]:
df["country"].value_counts()

country
US    9983
GB    3963
BR    3037
MX    2556
IN    2531
DE    2444
FR    1996
CA    1979
JP    1548
AU    1547
KR    1508
ES    1496
IT    1446
NG    1033
PH    1033
CL    1032
ZA    1022
TR    1011
ID     993
NL     990
SE     977
PL     954
CO     925
AR     910
TH     525
EG     519
MY     518
SG     514
PT     511
NZ     499
Name: count, dtype: int64

In [14]:
df["country"].nunique()

30

In [15]:
df["artist_name"].nunique()

500

In [16]:
df["artist_name"].value_counts().head(10)

artist_name
Knot Hart       12111
IsleEyre         5271
Ethereal         3232
Sterling Zen     2268
Rocco Ore        1709
SethStone        1486
ElaraRain        1111
ValeGlass         981
Frost Nova        862
The Dawns         750
Name: count, dtype: int64

In [17]:
df["track_id"].nunique()

50000

In [18]:
df["release_date"].head(10)

0    2021-10-06
1    2024-10-26
2    2022-11-12
3    2020-06-22
4    2024-01-22
5    2021-04-12
6    2025-07-16
7    2023-12-12
8    2020-06-17
9    2020-06-09
Name: release_date, dtype: str

In [19]:
df["popularity"].agg(["min", "max"])

min     0
max    92
Name: popularity, dtype: int64

In [20]:
df[["danceability", "energy"]].agg(["min", "max"])

     danceability  energy
min           0.0     0.0
max           1.0     1.0

In [21]:
df["key"].agg(["min", "max"])

min     0
max    11
Name: key, dtype: int64

In [22]:
df["mode"].value_counts().sort_index()

mode
0    17486
1    32514
Name: count, dtype: int64

In [23]:
df[["stream_count", "tempo"]].describe()

       stream_count         tempo
count  5.000000e+04  50000.000000
mean   1.183789e+05    119.067461
std    5.658443e+05     19.647807
min    1.000000e+02     60.000000
25%    4.979750e+03    105.990000
50%    1.595500e+04    118.575000
75%    6.068550e+04    131.350000
max    4.334502e+07    220.000000

In [24]:
df["explicit"].value_counts()

explicit
False    37576
True     12424
Name: count, dtype: int64

In [25]:
df["stream_count"].quantile([0.50, 0.75, 0.90, 0.95, 0.99, 1.00])

0.50       15955.00
0.75       60685.50
0.90      217474.40
0.95      466776.95
0.99     1751958.93
1.00    43345015.00
Name: stream_count, dtype: float64

## Resumen de la exploración inicial

- El dataset contiene 50,000 registros y 33 columnas.
- No se encontraron valores nulos.
- No se encontraron filas duplicadas.
- Los 50,000 `track_id` son únicos.
- El dataset contiene 500 artistas, 20 géneros y 30 países.
- Los datos abarcan los años 2020–2025, con una distribución relativamente equilibrada por año.
- Algunas categorías, especialmente géneros y artistas, presentan una distribución desigual.
- `release_date` está almacenada como texto (`str`) y deberá convertirse a tipo fecha.
- `popularity`, `danceability`, `energy`, `key` y `mode` cumplen los rangos esperados.
- `stream_count` presenta una distribución fuertemente sesgada, con valores extremos altos que deberán analizarse antes de decidir cualquier tratamiento.